[tool.ruff]
select = ["ALL"]

ignore = [
	"D211",
	"D213"
]

exclude = [
	".ruff_cache",
	"venv",
	"migrations"
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402","F401"]
"routes.py" = ["ANN201"]
