"""add title and expand body on posts table

Revision ID: a27f9e9361c1
Revises: 7c5b7321e7d2
Create Date: 2023-04-13 17:34:13.854280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27f9e9361c1'
down_revision = '7c5b7321e7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
